# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Docker@1
  displayName: 'Build docker image'
  inputs:
     command: Build an image
     imageName: 'cryxy/my-owntracks-recorder:1.0.0-snapshot'
     includeLatestTag: true
- task: Docker@1
  displayName: Login to docker
  inputs:
    command: login
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: 'DockerHub'
- task: Docker@1
  displayName: 'Push the image to docker hub'
  inputs:
    command: Push an image
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: 'DockerHub'
    imageName: 'cryxy/my-owntracks-recorder:1.0.0-snapshot'
    includeLatestTag: true
- task: maikvandergaag.maikvandergaag-file-to-variable@2.2.1
  displayName: 'Read version to variable'